### ISSUE TITLE
.include directive messes up with syntax highlighting

### ISSUE THREAD

**Issue by john5f35** [dan-c-underwood/vscode-arm#1]
There is some problem with .include directive.
If I do
```ARM
.include "macros.s"
```
It doesn't correctly recognise the string "macros.s", and it messes up with the syntax highlighting with the rest of the file.

Can you please fix this ASAP?

Also is this extension still actively managed? We are using this extension for a university course. We might want to add more features. Would it be okay if we use some of the code from this repo (it will be acknowledged based on the MIT license)?

**Comment by dan-c-underwood** [comment]
Hi John,

I’ll take a look this weekend and see if I can find the problem.

I’m still in a place to manage the repo but I don’t have as much time to put active development time towards it. Perfectly happy for you to pull code out under the terms of the license 🙂 any upstream changes would be very much appreciated where possible.

**Comment by john5f35** [comment]
OK, thanks! :)

**Comment by dan-c-underwood** [comment]
It should now be fixed in version 0.2.0 in the Marketplace - let me know if there are any issues. I've also added in invalid string detection and get as a synonym for include.
