### ISSUE TITLE
Highlighting incorrectly colors digits at the end of a symbol

### ISSUE THREAD

**Issue by Lokathor** [dan-c-underwood/vscode-arm#12]
In code such as
```
ldr r1, =(Mode3 | DisplayBG2)
```
The `3` and the `2` will be colored green like an immediate value, but in this case they're part of the symbol name.

**Comment by dan-c-underwood** [comment]
This should now be fixed in v1.3.0. Thanks for spotting this!

**Comment by Lokathor** [comment]
I updated to 1.3 and the other two issues were fixed but this one was not.

![Screenshot 2020-04-11 17 01 35](https://user-images.githubusercontent.com/5456384/79056704-49f2e000-7c16-11ea-9411-16546e27db0d.png)

**Comment by dan-c-underwood** [comment]
Thanks for spotting. I believe this is now fixed in v1.3.1.
