### ISSUE TITLE
`.thumb` and `.set` directives have no color

### ISSUE THREAD

**Issue by Lokathor** [dan-c-underwood/vscode-arm#14]
Many of the common assembler directives have a color, but these two do not, despite them both being quite commonly used.

**Comment by dan-c-underwood** [comment]
This should now be fixed in v1.3.0. Thanks for spotting this! (I'm not sure how I or anyone else didn't spot that `thumb` wasn't covered. I've now added it into the test file to reduce risk of regression. 😄
