### ISSUE TITLE
Support for pre-UAL syntax?

### ISSUE THREAD

**Issue by lunasorcery** [dan-c-underwood/vscode-arm#16]
In UAL syntax, conditional byte reads are formatted as LDRB(cond), which this supports.
In pre-UAL syntax, it's formatted as LDR(cond)B, which this extension currently doesn't support.
This also applies to LDRH/STRB/STRH/etc.

Is there any chance we can get support for this added?

**Comment by dan-c-underwood** [comment]
I've just added this in v1.4.0. Let me know if there are any issues 😄

**Comment by lunasorcery** [comment]
Looks good to me, thank you!
