### ISSUE TITLE
Publishing to Open VSX

### ISSUE THREAD

**Issue by proninyaroslav** [dan-c-underwood/vscode-arm#17]
Hi. It would be nice if you publish the extension on Open VSX https://open-vsx.org/. I'm using VSCodium and it uses Open VSX by default.

**Comment by dan-c-underwood** [comment]
Done 😄 

https://open-vsx.org/extension/dan-c-underwood/arm

I can't promise I'll remember to update it - so if you spot that the version number is lagging behind please let me know!

**Comment by proninyaroslav** [comment]
Thank you!
