### ISSUE TITLE
Language id is too generic & overlap's with other (different assembly syntaxes)

### ISSUE THREAD

**Issue by osterhoutan** [dan-c-underwood/vscode-arm#23]
## The Problem
You have opted to use the very non-descript string `asm` as the id for the language you are contributing. 

But since "asm" is just short for assembly and needless to say there is a different assembly for syntax for every architecture, and often multiple syntax standards for different assemblers/standards.

So it is ambiguous, which is not such a great thing.

I recognize that even if you and everyone else who is using `asm` as the language id in vscode for their chosen assembly syntax, there would be still be ambiguity in that the file extensions would still have overlap, but this isn't that big of a deal since you can manually change the language of an open file.

Which really only makes the overlap even worse since now the only way to change which extension is offering the language server, is to either only have one of the extensions enabled, or hope that one of the extensions using the contributing the `asm` language id, allow you to configure which language server to use (not likely).
And this is not a good solution since it only allows one to be active per "workspace".

## The Solution
Change your language id and name to be more descriptive like `gnu-arm-asm`/`gnuarmasm`/`gnu-arm`/`gnuarm` for the id and "GNU ARM Assembly" for the name.
Since you are providing support for the GNU ARM Assembly syntax.

I am leaving similar issues on the repos of other offending extensions, so that this issue can be a thing of the past.

**Comment by dan-c-underwood** [comment]
Hi, thanks for submitting this. Unless I've missed something, the Language ID for this extension is currently (and has always been) `arm` not `asm`. So I'm therefore not sure what change you're requesting?

**Comment by dan-c-underwood** [comment]
Closing issue due to lack of response.
