### ISSUE TITLE
#definition with underscore gets commented

### ISSUE THREAD

**Issue by baileyherbert** [dan-c-underwood/vscode-arm#25]
I suspect that a regular expression needs a slight update. 😃 

```
ldrb w3, [x13, #ired]
ldrb w3, [x13, #i_red]
```

![image](https://user-images.githubusercontent.com/9532377/116645518-e9226c80-a92a-11eb-813e-2e2630185791.png)

**Comment by dan-c-underwood** [comment]
Should now be fixed in v1.5.1. Thanks for spotting it! 😄

**Comment by baileyherbert** [comment]
Awesome! Thanks for the swift patch and the sweet extension. Cheers & take care!
