### ISSUE TITLE
Why no sdiv/udiv highliting?

### ISSUE THREAD

**Issue by emilia-miki** [dan-c-underwood/vscode-arm#26]
sdiv and udiv are not highlighted. Is it intentional?

**Comment by dan-c-underwood** [comment]
Unintentional, fixed in v1.5.2 😄 Thanks for reporting!

**Comment by emilia-miki** [comment]
Actually, there is a lot of other instructions that are not highlighted by your extension. I'd love if you added all of them, but there are a few small caveats. 

Here is the [complete list of ARM instructions](https://gist.github.com/mykytko/dd0531e98ad43b725099284f3f38cd98) provided in your format. There are duplicates of already present instructions, and I can try to remove them from this file later. 

I see that you categorise the instructions for some purpose. I took the instructions from the official documentation on developer.arm.com and they are divided only into 3 sections: base instructions, SIMD and floating-point instructions and SVE instructions. My idea is to categorise the first section manually and leave the last 2 sections in 2 whole categories. Another minor problem is that there are some overlaps between the 3 sections, so we'll have to decide how to resolve them.
