### ISSUE TITLE
highlighting error for #if

### ISSUE THREAD

**Issue by ZCShou** [dan-c-underwood/vscode-arm#28]
I used it for U-Boot's crt0.s
![image](https://user-images.githubusercontent.com/8591065/148718345-2b3e3af7-74df-4437-80a1-5d3526289bc9.png)

**Comment by hongshui3000** [comment]
same issue
![image](https://user-images.githubusercontent.com/25566498/150674750-ff72112f-81de-41db-966b-4076468a5065.png)

**Comment by dan-c-underwood** [comment]
Should be fixed now in v1.7.2! 🙂
