### ISSUE TITLE
Looks like not work :(

### ISSUE THREAD

**Issue by Spider84** [dan-c-underwood/vscode-arm#29]
I just install extension, but it not wok :(
![image](https://user-images.githubusercontent.com/1863325/151493716-35b5a1eb-d09f-4050-a912-243948e0701c.png)

**Comment by hongshui3000** [comment]
The extension seems to only support GNU ARM assembly instructions

**Comment by dan-c-underwood** [comment]
Hi! The original instructions supported were those from the core Arm ISA and implemented within the GNU Arm toolchain. I'm perfectly happy to add in others on a case-by-case basis where it makes sense to. I'll try to capture these/adjacent ones - I assume they're from the Keil toolchain?

**Comment by dan-c-underwood** [comment]
Some commands added in v1.7.2!

**Comment by Spider84** [comment]
> Keil toolchain?

Yes.
Great!
