### ISSUE TITLE
highlighting error for #endif && wfi

### ISSUE THREAD

**Issue by hongshui3000** [dan-c-underwood/vscode-arm#30]
v1.7.2
![image](https://user-images.githubusercontent.com/25566498/152772996-4e7ecd51-e209-4029-9a07-08322045ae50.png)
![image](https://user-images.githubusercontent.com/25566498/152773743-e2a9673f-11ae-49f8-bb66-5c85c9f339de.png)
![image](https://user-images.githubusercontent.com/25566498/152775039-a4f47a13-6aff-4ad7-accf-9d835d51586d.png)

**Comment by dan-c-underwood** [comment]
Thanks! These should all be fixed in v1.7.3.
